### ISSUE TITLE
ERRORED FILE

### ISSUE THREAD

**Issue by javiburatos** [fonnymunkey/MaterialTweaker#1]
Hello, I have a problem with the mod and it is that when I enter the code in the configuration file, this code is deleted and this other file appears (I attach it here, it is an ERRORED file)

# Configuration file

general {
    DIAMOND,5,3000,14.0,10.0,15
    ##########################################################################################################
    # server
    #--------------------------------------------------------------------------------------------------------#
    # Server Config
    ##########################################################################################################

    server {
        # Print information about material attributes when they are registered.
        B:"Print Material Info"=false
    }

}

**Comment by fonnymunkey** [comment]
You are editing the wrong file, the files that have the instructions and that you edit are in the "config/materialtweaker" folder.
You simply add a new line below the instructions and add your lines there.

**Comment by javiburatos** [comment]
sorry, I,m very stupid. Thanks, it works now. I have another question, this mod is compatible with other mods? for example If I wanted to change materials from other mods?

**Comment by fonnymunkey** [comment]
Yes, if you enable the "Print Material Info" config option and then launch the game, you can see the names and information of all the materials registered by mods when they get registered while the game is loading.

**Comment by javiburatos** [comment]
perfect, very thanks
